version: '3'
services:
  # Backend Java + Bancos
  java:
    build:
      context: ./agro-radar-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_radar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: agro_radar
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\""]
      interval: 5s
      timeout: 5s
      retries: 5

  # Frontend Next.js
  nextjs:
    build:
      context: ./agro-radar-next-new
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - java  # Espera o Java subir primeiro

  # Proxy Nginx
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - java