version: '3.8'

services:
  java:
    build:
      context: ./agro-radar-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy  # Dependência do PostgreSQL

  nextjs:
    build:
      context: ./agro-radar-next-new
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:  # SERVIÇO NGINX MANTIDO
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - java

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_radar
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # #############################################
  # MongoDB (Comentado)
  # #############################################
  
  mongo:
     image: mongo:latest
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: root
       MONGO_INITDB_DATABASE: agro_radar
     ports:
       - "27017:27017"