version: '3'
services:
  # Serviço Java + Dependências
  java:
    build:
      context: ./agro-radar-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_radar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: agro_radar
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\""]
      interval: 5s
      timeout: 5s
      retries: 5

  # Outros serviços (comentados inicialmente)
  # nextjs:
  #   build: ./agro-radar-next-new
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - java

  # node:
  #   build: ./agro-radar-node
  #   ports:
  #     - "3001:3001"

  # proxy:
  #   build: ./nginx
  #   ports:
  #     - "80:80"